### ISSUE TITLE
overwrites imgurup

### ISSUE THREAD

**Issue by ghost** [Pirater12/website-forwarder#1]
every time i tried to install it via fbi, it wont appear to install it. when i rebooted it still won't appear.

**Comment by hax0kartik** [comment]
Are you using a custom website forwarder or the /r/3dshacks one?

**Comment by ghost** [comment]
wait it overwrite over imgurup :/ and im using the 3dshacks one

**Comment by ghost** [comment]
You should probably change the titleid for the 3dshacks one lmao

**Comment by hax0kartik** [comment]
Lmao, looks like i forgot to change the titleid.Thanks for reporting!
